import pytest

import try_datetime

try_datetime.secti
try_datetime.test_secti

def test_tah_chyba():
    with pytest.raises(ValueError):
        try_datetime.assert_called_with(3,4)